apiVersion: v1
kind: Service
metadata:
  name: prime-backend-app
  labels:
    app: prime-backend-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: prime-backend-app

