apiVersion: v1
kind: Service
metadata:
  name: prime-frontend-app
  labels:
    app: prime-frontend-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: prime-frontend-app

